### ISSUE TITLE
0.9.5 To-do List

### ISSUE THREAD

**Issue by stephendade** [stephendade/Rpanion-server#116]
V0.9.5 will be primarily a bug-fix release. Aiming for release in mid-2023

- [x]  Adhoc Wifi does not persist across reboots
- [x]  Ubuntu: Migrate from 20.04 to 22.04
- [x]  Use new Ras Pi libcamera API for video streaming
- [ ]  ~~Username/password protection~~ _Requires significant refactor ... so leaving this for a future version_
- [x]  64-bit support
- [ ]  More help text
- [ ]  ~~Default to hotspot if no saved Wifi networks in range~~
- [x]  Hardware x264 acceleration for v4l2 sources
- [x]  Wireguard VPN shows unknown for working connections
- [x]  Need refresh on networking display. Not always latest
- [x]  Slow shutdown on Ubuntu ~90sec.
- [x]  Network connections don't show up quite right on Ubuntu
- [X]  Add support for CSI cameras on Jetson
- [x]  Ubuntu 20 appears to have lost CSI camera

**Comment by stephendade** [comment]
For everyone watching this issue - barring no major issues, I'll plan to get 0.9.5 out in the next couple of weeks.

**Comment by stephendade** [comment]
Ended up versioning this at 0.10.0. Anyways, it's now been released (see 'releases' tab for the disk image) and just need to update the documentation and do the announcements
